workflows:
  upload_ios_metadata:
    name: Upload iOS metadata
    instance_type: mac_mini_m1
    max_build_duration: 45

    environment:
      xcode: 16.2
      groups:
        # тут мають лежати APPSTORE_ISSUER_ID, APPSTORE_KEY_ID, APPSTORE_P8, APPLE_EMAIL
        - appstore-connect
      vars:
        IOS_BUNDLE_ID: com.solkovalproj.app
        APP_NAME: Highway Story

    scripts:
      - name: Print working dir & contents
        script: |
          echo "PWD: $(pwd)"
          ls -R

      - name: Install Ruby dependencies
        script: |
          bundle install || bundle install --path vendor/bundle
          gem install fastlane-plugin-appicon || true

      - name: Validate metadata directory structure
        script: |
          echo "===== Validating Metadata ====="
          # Check that metadata folder exists
          if [ ! -d "./fastlane/metadata" ]; then
            echo "ERROR: Metadata directory not found at ./fastlane/metadata"
            exit 1
          fi
          
          # Check that en-US folder exists (primary required locale)
          if [ ! -d "./fastlane/metadata/en-US" ]; then
            echo "ERROR: No en-US metadata folder found in ./fastlane/metadata"
            exit 1
          fi
          
          # List and count all locale folders
          echo "Scanning metadata locales..."
          find ./fastlane/metadata -maxdepth 1 -type d | grep -v "^./fastlane/metadata$" | grep -v "review_information" | sort | while read LOCALE_DIR; do
            LOCALE=$(basename "$LOCALE_DIR")
            echo "Processing metadata locale: $LOCALE"
            
            # Check for required metadata files in each locale
            REQUIRED_FILES=("name.txt" "description.txt" "keywords.txt")
            MISSING=0
            for FILE in "${REQUIRED_FILES[@]}"; do
              if [ ! -f "$LOCALE_DIR/$FILE" ]; then
                echo "  - WARNING: $FILE is missing in $LOCALE"
                MISSING=$((MISSING+1))
              fi
            done
            
            if [ $MISSING -eq 0 ]; then
              echo "  - All required files present in $LOCALE"
            else
              echo "  - $MISSING required files missing in $LOCALE"
            fi
          done
          
          # Verify required files exist in en-US (this is a must)
          REQUIRED_FILES=("name.txt" "description.txt" "keywords.txt" "privacy_url.txt" "support_url.txt")
          for FILE in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "./fastlane/metadata/en-US/$FILE" ]; then
              echo "ERROR: Required metadata file ./fastlane/metadata/en-US/$FILE is missing"
              exit 1
            fi
          done
          
          # Count language folders
          LANGUAGE_FOLDERS=$(find ./fastlane/metadata -maxdepth 1 -type d | grep -v "^./fastlane/metadata$" | grep -v "review_information" | wc -l)
          echo "Found $LANGUAGE_FOLDERS language folders in metadata"
          
          # Check for review_information
          if [ -d "./fastlane/metadata/review_information" ]; then
            echo "Review information folder found"
            REVIEW_FILES=$(find "./fastlane/metadata/review_information" -type f | wc -l)
            echo "Found $REVIEW_FILES files in review_information"
          else
            echo "WARNING: No review_information folder found - this might be needed for new app submissions"
          fi
          
          echo "Metadata validation successful!"

      - name: Upload metadata via fastlane deliver
        script: |
          bundle exec fastlane ios upload_metadata

    artifacts:
      - fastlane/logs/**/*

    #це потрібно, щоб отримувати сповіщення по пошту
    #publishing:
    #  email:
    #    recipients:
    #      - $APPLE_EMAIL
    #    notify:
    #      success: true
    #      failure: true
